In [2]:
import numpy as np

In [3]:
import pandas as pd

In [7]:
l=[1,2,3,4,54]

In [8]:
np.asarray(l)

array([ 1,  2,  3,  4, 54])

In [ ]:
#Digits functions

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
# no function exist after ones 

In [19]:
#practice

In [21]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [22]:
np.empty((4,5))

array([[8.23603207e-01, 2.01539546e-01, 6.20192574e-05, 3.81188746e-01,
        4.93584584e-01],
       [9.11645681e-01, 7.69337283e-02, 3.07293156e-02, 5.26368062e-01,
        3.75818553e-01],
       [4.42378877e-01, 2.46037629e-01, 7.97128057e-01, 5.73263387e-02,
        9.92394869e-01],
       [4.84849082e-01, 1.33690368e-01, 3.32257915e-01, 2.12053530e-01,
        5.45026649e-01]])

In [24]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [25]:
np.linspace(2,6,10)          # 10 numbers between 2 to 6

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [26]:
a=np.linspace(2,6,10)        #coverting into 2D Array

In [28]:
a.reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [35]:
np.linspace(2,6,10,endpoint=False).reshape(5,2)     #endpoint

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [37]:
np.linspace(2,6,10,endpoint=False,retstep=True)       #retstep

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [38]:
np.linspace(2,6,100,endpoint=False,retstep=True) 

(array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16,
        4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 ,
        4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04,
        5.08, 5.12, 5.16, 5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48,
        5.52, 5.56, 5.6 , 5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92,
        5.96]),
 0.04)

In [4]:
a=np.arange(4,20).reshape(4,4)        #creating new 2D-array

In [5]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
a.max()                             #max

19

In [17]:
a=np.arange(4,40).reshape(6,6)        #creating new 2D-array

In [18]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [19]:
a.max()                              #max

39

In [20]:
a.max(axis=0)                         #searching coloumns

array([34, 35, 36, 37, 38, 39])

In [21]:
a.max(axis=1)                       #searching rows

array([ 9, 15, 21, 27, 33, 39])

In [23]:
a/0                     #zerodivision

C:\Users\rumma\AppData\Local\Temp/ipykernel_22164/4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [24]:
a**2                    #square

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [25]:
pow(a,4)           #power function

array([[    256,     625,    1296,    2401,    4096,    6561],
       [  10000,   14641,   20736,   28561,   38416,   50625],
       [  65536,   83521,  104976,  130321,  160000,  194481],
       [ 234256,  279841,  331776,  390625,  456976,  531441],
       [ 614656,  707281,  810000,  923521, 1048576, 1185921],
       [1336336, 1500625, 1679616, 1874161, 2085136, 2313441]],
      dtype=int32)

In [30]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [29]:
10+a                           #addition

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [34]:
b=np.array([2,3,1,2,3,2]) #creating an array-b

In [35]:
a+b                      #Adiing through rows an array-b in array-a 

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [36]:
b.T    

array([2, 3, 1, 2, 3, 2])

In [37]:
b+a                 #adding through coloumn     #note; answer would be same

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [41]:
b=b.reshape(6,1)    #converting b-array to 2D-array

In [42]:
b

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [43]:
b+a                    #adding 

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [10]:
a=np.arange(4,40).reshape(3,6,2)    #creating new 3D-array

In [11]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [12]:
a.max()

39

In [15]:
a.max(axis=1)            #row wise search

array([[14, 15],
       [26, 27],
       [38, 39]])

In [1]:
max(a.max(axis=0))            #coloumn wise search 

NameError: name 'a' is not defined

In [44]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [45]:
np.sqrt(a)   #square root

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [46]:
np.exp(a)          #exponents

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [3]:
np.log10(a)           #log

NameError: name 'np' is not defined

In [50]:
x=np.array([1,2,3])    #create an array
x

array([1, 2, 3])

In [51]:
y=x                #copying in y with same space (this is called shallow copy)

In [52]:
y

array([1, 2, 3])

In [53]:
z=np.copy(x)       #copying in z with different space (this is called deep copy)

In [54]:
z

array([1, 2, 3])

In [55]:
x[0]=100          #replacing 1 with 100

In [56]:
x

array([100,   2,   3])

In [57]:
y               #same space

array([100,   2,   3])

In [58]:
z               #different space

array([1, 2, 3])

In [59]:
id(x)           #identity

1772845749424

In [60]:
id(y)         #id is same 

1772845749424

In [61]:
id(z)        # id is different 

1772845751728

In [62]:
id(x[0])         #lement id

1772845777808

In [63]:
id(y[0])           #different element id

1772845777392

In [65]:
id(x[0])==id(y[0])       #number is different but id is same 

True

In [66]:
id(x[0])==id(y[1])     #element is different but id is same 

True

In [64]:
id(z[0])          #different element id

1772845778320