In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
from sklearn.naive_bayes import GaussianNB

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score, roc_curve

In [7]:
import matplotlib.pyplot as plt

In [12]:
data = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv')

In [13]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [14]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [27]:
x = data.drop(columns = ['Outcome'])

In [28]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [29]:
 y = data.Outcome

In [30]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [34]:
scaler = StandardScaler()

In [35]:
x_scaled = scaler.fit_transform(x)

In [37]:
x_train , x_test , y_train , y_test = train_test_split(x_scaled , y , test_size = .25 ,random_state = 30)

In [38]:
x_train

array([[ 0.3429808 ,  0.22238089,  0.56322275, ...,  0.33093202,
        -0.99022534,  1.00055664],
       [ 0.63994726, -1.12339636,  0.45982725, ..., -0.10059342,
        -0.2714371 ,  0.74529338],
       [ 0.04601433,  0.72313521,  0.66661825, ...,  0.82591707,
         0.24802331,  0.31985461],
       ...,
       [-0.25095213,  0.22238089,  0.45982725, ..., -1.3824778 ,
        -0.61573063,  1.85143417],
       [-0.54791859, -0.12188771,  1.08020025, ..., -0.86210889,
        -0.47982529, -1.04154944],
       [-0.54791859, -0.84172205, -0.05715025, ..., -0.76057349,
         0.26916414, -1.04154944]])

In [39]:
x_test

array([[-1.14185152, -0.62264204,  0.35643175, ...,  0.47054319,
        -0.82713894, -0.61611067],
       [-0.25095213, -0.46615631, -0.78091875, ..., -0.13866919,
        -0.54324778, -0.78628618],
       [ 1.82781311, -1.43636781,  0.66661825, ...,  0.165937  ,
        -0.63083122,  0.40494237],
       ...,
       [-0.54791859,  0.12848945, -0.47073225, ...,  0.22939662,
        -1.15935199, -0.19067191],
       [ 0.04601433,  0.5040552 ,  0.77001375, ..., -0.10059342,
        -0.66405253, -0.27575966],
       [ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ]])

In [40]:
y_train

628    0
176    0
417    1
236    1
334    0
      ..
145    0
763    0
140    0
500    0
421    0
Name: Outcome, Length: 576, dtype: int64

In [41]:
y_test

226    0
610    0
505    0
470    0
474    0
      ..
677    0
762    0
135    0
351    0
0      1
Name: Outcome, Length: 192, dtype: int64

In [43]:
naive_bayes = GaussianNB()

In [50]:
naive_bayes.fit(x_train,y_train)

GaussianNB()

In [52]:
naive_bayes.predict(x_test)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [51]:
naive_bayes.score(x_test , y_test)

0.7916666666666666