In [48]:
import numpy as np
import pandas as pd

In [2]:
#1-D Array
l=['sudh',1,2,3,4]
l

['sudh', 1, 2, 3, 4]

In [3]:
#Method-1
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [4]:
#Method-2
np.asarray(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [5]:
#Method-3
np.asanyarray(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [6]:
#dtype
t=np.array([1,2,3])
type(t)

numpy.ndarray

In [10]:
#Dimension
l=[1,2,3,4]

In [11]:
#1-d
np.array(l,ndmin=0)

array([1, 2, 3, 4])

In [12]:
#1-d
np.array(l,ndmin=1)

array([1, 2, 3, 4])

In [13]:
#2-d
np.array(l,ndmin=2)

array([[1, 2, 3, 4]])

In [14]:
#3-d
np.array(l,ndmin=3)

array([[[1, 2, 3, 4]]])

In [17]:
#get the value 1 from 4-d
arr = np.array([1,2,3,4],ndmin=4)
arr[0][0][0][0]

1

In [20]:
#upcasting everything(default)
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [23]:
#2-d array create

In [25]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [30]:
arr[1][0]

3

In [31]:
#create Matrices

In [32]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [33]:
#Fromfunction

In [34]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [37]:
np.mat(np.fromfunction(lambda i,j:i*j,(3,3))) #convert into matrix

matrix([[0., 0., 0.],
        [0., 1., 2.],
        [0., 2., 4.]])

In [39]:
#3-D Array
a = np.fromfunction(lambda i,j,z:i*j*z,(4,3,2),dtype=int)    # 4layers , 3rows, 2columns
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [40]:
a.ndim

3

In [42]:
a.size

24

In [43]:
a.shape

(4, 3, 2)

In [ ]:
#Note:You can convert only 2-D array into DataFrame not 3-D and 4-D

In [49]:
a = np.fromfunction(lambda i,j:i*j ,(400,100),dtype=int)
a

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [50]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [51]:
#Random Function

In [54]:
#rand
np.random.rand(4,4)

array([[0.78421438, 0.23415519, 0.30347774, 0.21528265],
       [0.33962904, 0.92389323, 0.96986579, 0.85851185],
       [0.53906762, 0.77908203, 0.88198841, 0.99356543],
       [0.50319947, 0.09845902, 0.75076553, 0.34857735]])

In [61]:
#randint
np.random.randint(4,50)

41

In [62]:
#randn
np.random.randn(4,5)

array([[-0.1044067 , -0.78003919,  0.20924692, -0.5395112 , -0.14191227],
       [ 2.07323768,  0.89038062, -1.84369486,  0.07583429, -0.34631216],
       [ 0.67447918,  1.20961808, -0.24151997,  0.4009789 , -1.06703611],
       [ 0.40922139, -1.16896683,  0.03042749, -1.32592917, -1.74304295]])

In [64]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.286046 -0.680069  1.532392  0.134595  0.039764
1  1.237407  0.593830  0.411111 -0.216618 -1.899100
2 -0.337969 -0.559074  0.618038 -0.953600  0.678419
3 -0.301674 -0.821866  0.307424  1.858848 -0.980535

In [65]:
#Reshape

In [66]:
a = np.fromfunction(lambda i,j,z:i*j*z,(4,3,2),dtype=int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [68]:
a.reshape(2,12)  #converting 3-D array into 2-D array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [70]:
#Manual
a.reshape(4,3,1,2)

array([[[[0, 0]],

        [[0, 0]],

        [[0, 0]]],


       [[[0, 0]],

        [[0, 1]],

        [[0, 2]]],


       [[[0, 0]],

        [[0, 2]],

        [[0, 4]]],


       [[[0, 0]],

        [[0, 3]],

        [[0, 6]]]])

In [71]:
#Range

In [72]:
list(range(4,10,2))

[4, 6, 8]

In [73]:
list(range(4,10,0.2)) #Range doesnot take float input

TypeError: 'float' object cannot be interpreted as an integer

In [76]:
#Arange(Fix)
np.arange(4,10,2)

array([4, 6, 8])

In [77]:
np.arange(4,10,0.2) #Arange(takes float values)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [78]:
#Digit function

In [79]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [80]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [82]:
#ADD

In [85]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [86]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [89]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [91]:
#Empty function
np.empty((4,5))

array([[-0.1044067 , -0.78003919,  0.20924692, -0.5395112 , -0.14191227],
       [ 2.07323768,  0.89038062, -1.84369486,  0.07583429, -0.34631216],
       [ 0.67447918,  1.20961808, -0.24151997,  0.4009789 , -1.06703611],
       [ 0.40922139, -1.16896683,  0.03042749, -1.32592917, -1.74304295]])

In [95]:
#Linspace function
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [98]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [100]:
np.linspace(2,6,10,endpoint=False)  #endpoint will end the repetation

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6])

In [101]:
np.linspace(2,6,10, endpoint=False,retstep=True)  #Step jump

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [102]:
#important function in np

In [105]:
#Max value
np.max([1,2,3])

3

In [111]:
#zerodivision
a= np.arange(4,40).reshape(6,6)
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [112]:
a/0

C:\Users\rumma\AppData\Local\Temp/ipykernel_16320/4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [113]:
#Square
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [114]:
#squareroot
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [115]:
#Power function
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [116]:
#Exponents
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [120]:
#log
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [121]:
#ID

In [122]:
x = np.array([1,2,3])

In [123]:
y = x

In [124]:
id(x)

2770783023440

In [125]:
id(y)

2770783023440

In [126]:
id(x)==id(y)

True

In [131]:
id(x[0])

2770782938992

In [132]:
id(y[0])

2770782939408

In [133]:
id(x[0])==id(y[0])

True

In [134]:
z = np.array([1,2,3])

In [135]:
id(x)==id(z)

False

In [136]:
id(x[0])==id(z[0])

True